---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/articles":
    get:
      summary: Index
      tags:
      - Articles
      parameters:
      - name: Authentication
        in: header
        schema:
          type: string
      responses:
        '200':
          description:
            description: Return all the available articles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    body:
                      type: string
        '401':
          description:
            description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      properties:
                        code:
                          type: integer
                          example: 401
                        message:
                          type: string
                          example: Not Authorized
  "/api/v1/articles/{id}":
    get:
      summary: Show
      tags:
      - Articles
      parameters:
      - name: Authentication
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
            description: article found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  body:
                    type: string
                  published:
                    type: boolean
                required:
                - id
                - title
                - body
                - published
        '404':
          description:
            description: article not found
          content: {}
        '401':
          description:
            description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      properties:
                        code:
                          type: integer
                          example: 401
                        message:
                          type: string
                          example: Not Authorized
  "/api/v1/authenticate":
    post:
      summary: Authenticate
      tags:
      - Sessions
      parameters: []
      responses:
        '201':
          description:
            description: user logged
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                required:
                - email
                - password
        '401':
          description:
            description: authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email or password
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
  "/api/v1/users":
    get:
      summary: Index
      tags:
      - Users
      parameters:
      - name: Authentication
        in: header
        schema:
          type: string
      responses:
        '200':
          description:
            description: Return all the available users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    email:
                      type: string
        '401':
          description:
            description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      properties:
                        code:
                          type: integer
                          example: 401
                        message:
                          type: string
                          example: Not Authorized
    post:
      summary: Create
      tags:
      - Users
      parameters:
      - name: Authentication
        in: header
        schema:
          type: string
      responses:
        '201':
          description:
            description: user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        '422':
          description:
            description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email or password
                required:
                - error
        '401':
          description:
            description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      properties:
                        code:
                          type: integer
                          example: 401
                        message:
                          type: string
                          example: Not Authorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/users/{id}":
    get:
      summary: Show
      tags:
      - Users
      parameters:
      - name: Authentication
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
            description: Return the selected user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                required:
                - id
                - email
        '404':
          description:
            description: user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Page not found
        '401':
          description:
            description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      properties:
                        code:
                          type: integer
                          example: 401
                        message:
                          type: string
                          example: Not Authorized
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
