---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/articles":
    get:
      summary: Index
      tags:
      - Articles
      responses:
        '200':
          description:
            description: Return all the available articles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    body:
                      type: string
  "/api/v1/articles/{id}":
    get:
      summary: Show
      tags:
      - Articles
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
            description: article found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  body:
                    type: string
                required:
                - id
                - title
                - body
        '404':
          description:
            description: article not found
          content: {}
  "/api/v1/users":
    get:
      summary: Index
      tags:
      - Users
      security:
      - basic_auth: []
      responses:
        '200':
          description:
            description: Return all the available users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    email:
                      type: string
    post:
      summary: Create
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description:
            description: user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        '422':
          description:
            description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/users/{id}":
    get:
      summary: Show
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
            description: Return the selected user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                required:
                - id
                - email
        '404':
          description:
            description: user not found
          content: {}
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: query
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
